### ISSUE TITLE
mixer-api 301 issue

### ISSUE THREAD

**Issue by ProFire** [CakeDC/mixer#10]
I'm using firefox mainly for development. I notice that http://mixer-api.cakedc.com/ returns 301 code to https://mixer-api.cakedc.com/. In javascript, the javascript does not seem to be redirecting properly. If I copy the url on my browser, it is redirecting properly.

Perhaps, you could do a hardcoded https in the code instead?

**Comment by andrej-griniuk** [comment]
This should be solved now, we've removed forced redirect to https.
