### ISSUE TITLE
Plugins with non existent git repos.

### ISSUE THREAD

**Issue by ADmad** [CakeDC/mixer#13]
Checking mixer today it listed `qobo/cakephp-cms` and `guilherme/stock-cake-son` under "New releases" and "New plugins" respectively. I tried having a look at their repos which both resulted in 404s: https://github.com/qobo/cakephp-cms, https://github.com/guilherme/stock-cake-son.

So I guess some extra checks are needed to remove just repos from the list.

**Comment by ADmad** [comment]
Another related issue: I searched for "shadow" and got results `ad7six/shadow-translate` and `daoandco/shadow-translate`. The latter again doesn't have a git repo anymore. Probably someone's temporary fork.

It would be nice if such non existent repos or forks would not be listed by mixer.

**Comment by andrej-griniuk** [comment]
Fixed. GitHub URL shown was wrong.
