### ISSUE TITLE
"Kitchen" is broken on anything but MySQL

### ISSUE THREAD

**Issue by dakota** [CakeDC/mixer#15]
"Kitchen" relies only on the `SHOW TABLES` sql to determine what tables are available in the database. This syntax only works with MySQL meaning that it is unusable with any other database engine.

It should instead use the `listTables()` method that is provided by the ORM.

**Comment by dereuromark** [comment]
Also, please ignore the migrations tables..
"a_dmad_hybrid_auth_phinxlog" is not sth I would ever want to bake :)

**Comment by dakota** [comment]
Should probably just re-use/copy the code that bake uses to generate it's list of tables

**Comment by andrej-griniuk** [comment]
Good point! Done.
