### ISSUE TITLE
Uninstall cakedc/users fails

### ISSUE THREAD

**Issue by Isengo1989** [CakeDC/mixer#16]
Updated to the newest Version of CakePHP and Mixer - tried to uninstall users from cakedc - after 2 hours I closed the tab, because nothing seemed to happen.

**General**
Request URL:http://www.test.de/mixer/uninstall.json
Request Method:POST
Status Code:200 OK
Remote Address:127.0.0.1:80
Referrer Policy:no-referrer-when-downgrade

**Response Headers**
view source
Connection:keep-alive
Content-Type:application/json; charset=UTF-8
Date:Mon, 03 Jul 2017 20:42:21 GMT
Server:nginx/1.10.1 (Ubuntu)
Transfer-Encoding:chunked

CakePHP 3.4.9
Webserver NGINX
OS Ubuntu 16.04

Image: https://ibb.co/nnXrja

**Comment by andrej-griniuk** [comment]
Hi @Isengo1989 

a new version has been tagged, please try now.
