### ISSUE TITLE
dead plugins removal?

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/mixer#18]
there should probably be sth to also remove/disable dead ones:
/mixer/view/guilherme/stock-cake-son
gives a 404 on the github link to its repo http://github.com/guilherme/stock-cake-son

**Comment by dereuromark** [comment]
Maybe those are just wrongly generated links on the mixer side?

Because when you go to
/mixer/view/qobo/cakephp-search
The link to github there ( https://github.com/qobo/cakephp-search ) is also a dead one, but the link from composer (once you find your way there) is https://github.com/QoboLtd/cakephp-search which then works..

**Comment by andrej-griniuk** [comment]
Fixed. GitHub URL shown was wrong.
