### ISSUE TITLE
There should be a force-refresh button

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/mixer#21]
I suspect some cache being used.
New releases are not showing up even after minutes.
And the README and alike are also outdated after releases and you cannot get the fresh content
I tried http://...l/mixer/view/dereuromark/cakephp-ide-helper
And still got the old tags, after minutes.

A small force refresh or cache warm button might be useful here.

**Comment by dereuromark** [comment]
If the problem is packagist and there are no quicker updates from them, this might be also out of scope of mixer then :/

**Comment by andrej-griniuk** [comment]
We get that sort of data from GitHub and sync once in ~6h. We could bump it up to 1-2h, but hardly less due to GitHub API rate limits. But I'll add a "force refresh" button, that's fine.

**Comment by dereuromark** [comment]
Sure, you can also put a rate limit on the force refresh (only 1 per every x minutes possible etc) even.

**Comment by dereuromark** [comment]
Yes, please bump the updates to 1h etc. :) Thanks.

**Comment by dereuromark** [comment]
Did you already adjust the rate limit? It looks like it is still very long, and thus some releases are skipped as they fall out of it (and are replaced by upcoming ones due to the limit of the displayed items).

**Comment by dereuromark** [comment]
There must also be an issue with the "new releases" window
https://github.com/dereuromark/cakephp-ide-helper/releases/tag/0.11.1 has been released like 1 day ago, but 4h and 3 days are displayed, nothing it between.

**Comment by andrej-griniuk** [comment]
Another issue in repositories sync found and fixed. Sorry for you plugin being discriminated :)
Sync interval bumped up to 1h.

**Comment by dereuromark** [comment]
;) No worries, this just made it obvious that sth is wrong. Thanks for the feedback.
