### ISSUE TITLE
Error - package installer stuck with message "Please wait, it might take a bit.."

### ISSUE THREAD

**Issue by tymon82** [CakeDC/mixer#24]
{
    "message": "The source URI string appears to be malformed",
    "url": "\/mixer\/install.json",
    "code": 500,
    "file": "E:\\projects\\my_app\\vendor\\zendframework\\zend-diactoros\\src\\Uri.php"
,
    "line": 440
}

**Comment by ADmad** [comment]
I get the same error.

I think 6826f2079641f8d727feefc68a37430c9c9fe475 is the cause of this issue.

**Comment by andrej-griniuk** [comment]
Fixed in 1.1.1
