### ISSUE TITLE
Updating plugins moves them out of require_dev

### ISSUE THREAD

**Issue by cleptric** [CakeDC/mixer#3]
I updated bake and debug_kit through mixer and it moved the dependencies out of `require-dev` into `require`.
A way to configure that or any magic (certain plugins are always `require_dev`) would be highly appreciated 🙂

**Comment by dereuromark** [comment]
Maybe it can just keep it wherever it was :) That would be the wisest thing to do IMO.

**Comment by andrej-griniuk** [comment]
Fixed in the way @dereuromark said.
