### ISSUE TITLE
Mixer requires cakephp 3.4.*

### ISSUE THREAD

**Issue by Tomicapo** [CakeDC/mixer#30]
Mixer is not supported in CakePHP v3.5. 

$[...]/app>**composer require --dev cakedc/mixer**
Using version ^1.1 for cakedc/mixer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  **Problem 1**
    - cakedc/mixer 1.1.1 requires cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.0-RC1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0-RC4, 3.4.0-beta1, 3.4.0-beta2, 3.4.0-beta3, 3.4.0-beta4, 3.4.1,
3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9] but these conflict with your requirements or minimum-stability.
    - cakedc/mixer 1.1.0 requires cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.0-RC1, 3.4.0-RC2, 3.4.0-RC3, 3.4.0-RC4, 3.4.0-beta1, 3.4.0-beta2, 3.4.0-beta3, 3.4.0-beta4, 3.4.1,
3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9] but these conflict with your requirements or minimum-stability.
    - Installation request for cakedc/mixer ^1.1 -> satisfiable by cakedc/mixer[1.1.0, 1.1.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by andrej-griniuk** [comment]
Fixed.
