### ISSUE TITLE
https issues?

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/mixer#40]
The SSL certificate used to load resources from https://mixer-api.cakedc.com has been distrusted. See https://g.co/chrome/symantecpkicerts for more information.
main.js:1 GET https://mixer-api.cakedc.com/api/v1/packages?sort=last_week_stars&direction=desc&limit=5 net::ERR_CERT_SYMANTEC_LEGACY

Seems like it is broken now for normal local use.

**Comment by dereuromark** [comment]
Must be a glitch, now seems to work again somehow

**Comment by dereuromark** [comment]
I have the issues again.. net::ERR_CERT_SYMANTEC_LEGACY

**Comment by steinkel** [comment]
We've just switched to letsencrypt, please check again, thanks!

**Comment by dereuromark** [comment]
All good now, thx
